
DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'trae_app') THEN

      CREATE ROLE trae_app LOGIN PASSWORD 'TraeDev123!@#';
   END IF;
END
$do$;

GRANT USAGE ON SCHEMA public TO trae_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO trae_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO trae_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO trae_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO trae_app;
